apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: room-server-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: room-server-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: room-server
  namespace: default
roleRef:
  kind: Role
  name: room-server-role
  apiGroup: rbac.authorization.k8s.io